[window]
padding = { x = 0, y = 0 }
startup_mode = "Maximized"
decorations = "Buttonless"
option_as_alt = "OnlyRight"

[env]
# https://medium.com/@jogarcia/bring-on-the-true-color-on-alacritty-tmux-neovim-99134521731d
term = "xterm-256color"

[mouse]
hide_when_typing = true

[cursor]
# style = { shape = "Underline", blinking = "On" }

[selection]
save_to_clipboard = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 13

# Colors (Gruvbox dark)
[colors.primary]
background = "0x1d2021"
foreground = "0xebdbb2"

# Normal colors
[colors.normal]
black =    "0x282828"
red =      "0xcc241d"
green =    "0x98971a"
yellow =   "0xd79921"
blue =     "0x458589"
magenta =  "0xb16286"
cyan =     "0x689d6a"
white =    "0xa89984"

# Bright colors
[colors.bright]
black =    "0x928374"
red =      "0xfb4934"
green =    "0xb8bb26"
yellow =   "0xfabd2f"
blue =     "0x83a598"
magenta =  "0xd3869b"
cyan =     "0x8ec07c"
white =    "0xebdbb2"
